"""add profile to papers

Revision ID: abe41aa0fce5
Revises: e21b2626960b
Create Date: 2026-07-13 14:58:28.984718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe41aa0fce5'
down_revision: Union[str, Sequence[str], None] = 'e21b2626960b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'profile')
    # ### end Alembic commands ###
