"""add summary to papers

Revision ID: e21b2626960b
Revises: b38782471cf0
Create Date: 2026-07-13 14:39:53.311043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21b2626960b'
down_revision: Union[str, Sequence[str], None] = 'b38782471cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'summary')
    # ### end Alembic commands ###
